package syntax

const (
	Program    = "programa"
	EndProgram = "fimprog"
	If         = "se"
	Then       = "entao"
	Else       = "senao"
	Declare    = "declare"
	Read       = "leia"
	Write      = "escreva"
	Sum        = "+"
	Minus      = "-"
	Multiply   = "*"
	Divide     = "/"
	Greater    = ">"
	GEQ        = ">="
	Less       = "<"
	LEQ        = "<="
	IsEqual    = "=="
	Different  = "!="
	IntegerT   = "inteiro"
	FloatT     = "decimal"
	StringT    = "texto"
	BooleanT   = "bool"
)
